### ISSUE TITLE
페이지 히스토리 기능 건의

### ISSUE THREAD

**Issue by changhwa** [codechobostudy/springnote#1]
@devSejong 

당장 고민할 필요는 없는 주제인데용 생각난김에 던져둡니다.
페이지 히스토리 기능에서 diff, back 지원되면 좋겠어용 ㅎㅎ (머지는 힘들듯)

**Comment by devSejong** [comment]
네 말씀하신 내용 진행할 예정입니다.
파싱 결과화면을 diff하는건 힘들 것 같고, 마크다운을 비교하는 형식으로 할 예정입니다.
